## openms/manylinux is based on hroest/manylinux2014_qt59:v1.1
ARG CONTRIB_BRANCH_OR_TAG=${CONTRIB_BRANCH_OR_TAG}

FROM quay.io/pypa/manylinux2014_x86_64

RUN yum install -y wget
RUN yum install -y xz qt5-qtbase-devel 
RUN yum install -y qt5-qtbase-devel qt5-qtsvg qt5-qtsvg-devel python-devel 
RUN yum install -y libsvm-devel glpk-devel libzip-devel zlib-devel xerces-c-devel bzip2-devel sqlite-devel hdf5-devel
RUN yum install -y libtool

RUN yum install -y cmake3
RUN ln -s /usr/bin/cmake3 /usr/bin/cmake

# install contrib (need ALL here to build static libs)
RUN git clone -b ${CONTRIB_BRANCH_OR_TAG} --single-branch https://github.com/OpenMS/contrib.git && \
    mkdir contrib-build && \
    cd /contrib-build && \
    cmake -DBUILD_TYPE=ALL ../contrib && \
    rm -rf archives src && \
    cd / && \
    rm -rf contrib

WORKDIR /

# Metadata
LABEL base.image="manylinux2014_x86_64"
LABEL version="1.0"
LABEL software="OpenMS (dependencies for manylinux2010)"
LABEL software.version="qt5"
LABEL description="C++ libraries and tools for MS/MS data analysis"
LABEL website="http://www.openms.org/"
LABEL documentation="http://www.openms.org/"
LABEL license="http://www.openms.org/"
LABEL tags="Proteomics"

