
# Base Image
FROM ubuntu:22.04

# Metadata
LABEL base.image="ubuntu:22.04"
LABEL version="3.0"
LABEL software="OpenMS (dependencie, minimized)"
LABEL software.version="devel"
LABEL description="C++ libraries and tools for MS/MS data analysis"
LABEL website="http://www.openms.org/"
LABEL documentation="http://www.openms.org/"
LABEL license="http://www.openms.org/"
LABEL tags="Proteomics"

# Maintainer
MAINTAINER Hannes Rost <hroest@stanford.edu>

USER root

ENV cmakeversion 3.24
ENV cmakebuild 0

# Install Step 1: basic dependencies
RUN sudo apt-get -y update && \
         apt-get install -y --no-install-recommends --no-install-suggests g++ autoconf wget patch libtool make git automake && \
         apt-get install -y --no-install-recommends --no-install-suggests software-properties-common && \
         apt-get clean && \
         apt-get purge && \
         rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Install Step 2: obtain newer CMake

RUN echo https://cmake.org/files/v${cmakeversion}/cmake-${cmakeversion}.${cmakebuild}-linux-x86_64.sh
RUN sudo mkdir -p ~/temp && cd ~/temp && \
         wget https://cmake.org/files/v${cmakeversion}/cmake-${cmakeversion}.${cmakebuild}-linux-x86_64.sh && \
         mkdir -p /opt/cmake && \
         chmod +x cmake-${cmakeversion}.${cmakebuild}-linux-x86_64.sh && \
         sh cmake-${cmakeversion}.${cmakebuild}-linux-x86_64.sh --skip-license --prefix=/opt/cmake && ln -s /opt/cmake/bin/cmake /usr/local/bin/cmake && \
         rm -rf ~/temp

# Install Step 3: advanced dependencies
RUN sudo apt-get -y update && \
         apt-get install -y cmake && \
         apt-get install -y --no-install-recommends --no-install-suggests libsvm-dev libglpk-dev libzip-dev zlib1g-dev libxerces-c-dev libbz2-dev && \
         apt-get install -y --no-install-recommends --no-install-suggests libhdf5-dev && \
         apt-get install -y --no-install-recommends --no-install-suggests qtbase5-dev libqt5svg5-dev libqt5opengl5-dev && \
         apt-get install -y --no-install-recommends --no-install-suggests libboost-date-time-dev \
                                 libboost-iostreams-dev \
                                 libboost-regex-dev \
                                 libboost-math-dev \
                                 libboost-random-dev && \
         apt-get clean && \
         apt-get purge && \
         rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Install Step 5: Compiled dependencies
RUN git clone https://github.com/OpenMS/contrib.git && rm -rf contrib/.git/
RUN mkdir contrib-build

WORKDIR /contrib-build

RUN cmake -DBUILD_TYPE=EIGEN ../contrib && rm -rf archives src
RUN cmake -DBUILD_TYPE=COINOR ../contrib && rm -rf archives src

WORKDIR /
