
# Base Image (16.04) since we require GCC 4.9
FROM ubuntu:16.04

# Metadata
LABEL base.image="openms_dependencies"
LABEL version="1.3"
LABEL software="OpenMS (dependencies)"
LABEL software.version="devel"
LABEL description="C++ libraries and tools for MS/MS data analysis"
LABEL website="http://www.openms.org/"
LABEL documentation="http://www.openms.org/"
LABEL license="http://www.openms.org/"
LABEL tags="Proteomics"

# Maintainer
MAINTAINER Hannes Rost <hroest@stanford.edu>

USER root

ENV cmakeversion=3.14
ENV cmakebuild=5

# Install Step 1: basic dependencies
RUN sudo apt-get -y update && \
         apt-get install -y --no-install-recommends --no-install-suggests g++ autoconf patch libtool make git automake && \
         apt-get install -y --no-install-recommends --no-install-suggests software-properties-common python-software-properties && \
         apt-get clean && \
         apt-get purge && \
         rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Install Step 2: obtain cmake 3.x in ubuntu 16.04

RUN sudo mkdir ~/temp && cd ~/temp && \
         wget https://cmake.org/files/v$cmakeversion/cmake-$cmakeversion.$cmakebuild-Linux-x86_64.sh && \
         mkdir /opt/cmake && \
         sh cmake-$cmakeversion.$cmakebuild-Linux-x86_64.sh --prefix=/opt/cmake && ln -s /opt/cmake/bin/cmake /usr/local/bin/cmake

# Install Step 3: advanced dependencies
RUN sudo apt-get -y update && \
         apt-get install -y cmake && \
         apt-get install -y --no-install-recommends --no-install-suggests libsvm-dev libglpk-dev libzip-dev zlib1g-dev libxerces-c-dev libbz2-dev && \
         apt-get install -y --no-install-recommends --no-install-suggests libhdf5-dev && \
         apt-get install -y --no-install-recommends --no-install-suggests qtbase5-dev libqt5svg5-dev && \
         apt-get install -y --no-install-recommends --no-install-suggests libboost-date-time-dev \
                                 libboost-iostreams-dev \
                                 libboost-regex-dev \
                                 libboost-math-dev \
                                 libboost-random-dev && \
         apt-get clean && \
         apt-get purge && \
         rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Install Step 5: Compiled dependencies
RUN git clone https://github.com/OpenMS/contrib.git && rm -rf contrib/.git/
RUN mkdir contrib-build

WORKDIR /contrib-build

RUN cmake -DBUILD_TYPE=SEQAN ../contrib && rm -rf archives src
RUN cmake -DBUILD_TYPE=WILDMAGIC ../contrib && rm -rf archives src
RUN cmake -DBUILD_TYPE=EIGEN ../contrib && rm -rf archives src
RUN cmake -DBUILD_TYPE=COINOR ../contrib && rm -rf archives src
RUN cmake -DBUILD_TYPE=SQLITE ../contrib && rm -rf archives src

WORKDIR /
