FROM ubuntu:17.04

LABEL software="OpenMS contrib"
LABEL software.version="develop"
LABEL website="https://www.OpenMS.de"
LABEL documentation="https://www.OpenMS.de/documentation/"
LABEL tags="proteomics, mass spectrometry"
LABEL license="https://raw.githubusercontent.com/OpenMS/contrib/master/License.txt"
LABEL base.image="ubuntu:17.04"

# Step 1: set up a sane build system
USER root

RUN apt-get -y update
RUN apt-get install -y --no-install-recommends --no-install-suggests g++ autoconf automake patch libtool make git
RUN apt-get install -y --no-install-recommends --no-install-suggests software-properties-common python-software-properties

# Step 2: cmake (see below)

# Step 3: advanced dependencies
RUN apt-get install -y --no-install-recommends --no-install-suggests libsvm-dev libglpk-dev libzip-dev zlib1g-dev libxerces-c-dev libbz2-dev cmake
RUN apt-get install -y --no-install-recommends --no-install-suggests libboost-date-time1.62-dev \
                                                                     libboost-iostreams1.62-dev \
                                                                     libboost-regex1.62-dev \
                                                                     libboost-math1.62-dev \
                                                                     libboost-random1.62-dev

# Step 4: install Qt4
RUN apt-get install -y --no-install-recommends --no-install-suggests qt4-dev-tools qt4-default qt4-qtconfig qt4-qmake
RUN apt-get install -y --no-install-recommends --no-install-suggests libqt4-dev libqt4-opengl-dev libqt4-svg libqtwebkit-dev

###################################
# Step 5: install specific dependencies (previously compiled)
RUN apt-get install -y --no-install-recommends --no-install-suggests libwildmagic-dev \
         coinor-libcoinutils-dev coinor-libcgl-dev coinor-libcbc-dev \
         coinor-libclp-dev coinor-libosi-dev coinor-libvol-dev \
         seqan-dev libeigen3-dev libsqlite3-dev

# This makes the contrib package unnecessary

WORKDIR /

