#!/bin/bash

OPENMS_BRANCH="${SOURCE_BRANCH}"

## TODO with this custom build hook we could also use subfolders instead of branches to specify release Dockerfiles
docker build --build-arg OPENMS_BRANCH=$OPENMS_BRANCH -f $DOCKERFILE_PATH -t $IMAGE_NAME .

