#!/bin/bash

OPENMS_BRANCH="${SOURCE_BRANCH}"

# extract version
REGEX_VERSION='release\/([0-9]\.[0-9]\.[0-9])'

if [[ $OPENMS_BRANCH =~ $REGEX_VERSION ]]
then
  OPENMS_VERSION="${BASH_REMATCH[1]}"
else
  OPENMS_VERSION="latest"
fi

docker build --build-arg OPENMS_BRANCH=$OPENMS_BRANCH --build-arg OPENMS_VERSION=$OPENMS_VERSION -f $DOCKERFILE_PATH -t $IMAGE_NAME .
